# Generated by Django 5.2 on 2025-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
    ]
